
       SUBROUTINE PHOTORATES(PPFILE,LAMBDA,NLAMBDA,FLUX,RATE)
       
       IMPLICIT DOUBLE PRECISION (A-H,O-Z)

       DOUBLE PRECISION LAMBDA(NLAMBDA),FLUX(NLAMBDA)
       DOUBLE PRECISION LINE
       
       PARAMETER(N=400)

       CHARACTER*12 PPFILE
       
       COMMON/CROSS/NC,NL,WLL(400),SGL(400),WLC(400),SGC(400)

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C Open and read species file
C L=Line, C=Continuum
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
       
       OPEN (UNIT=1,FILE='Photo_Files/'//PPFILE)
             
       READ(1,*)
       
       READ(1,10) NL
       
       IF (NL.NE.0) THEN
          DO I=1,NL
             READ(1,11) WLL(I),SGL(I)
          END DO
       END IF
       
       READ(1,10) NC
       
       IF (NC.NE.0) THEN
          READ(1,*)
          DO I=1,NC
             READ(1,11) WLC(I),SGC(I)
          END DO
       END IF
       
       CLOSE (UNIT=1)
       
       
       CALL CALC_LINE(LAMBDA,NLAMBDA,FLUX,LINE)
       CALL CALC_CONT(LAMBDA,NLAMBDA,FLUX,CONT)
       
       RATE = LINE + CONT  
       
C Format statements
 10    FORMAT(I4)      
 11    FORMAT(4X,F8.1,1X,1PE10.3)  


CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C Return and exit subroutine
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
              
       RETURN       
       
       END SUBROUTINE PHOTORATES

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C Calculate photodissociation by line absorption
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
      
       SUBROUTINE CALC_LINE(LAMBDA,NLAMBDA,FLUX,LINE)

       IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      
       DOUBLE PRECISION LAMBDA(NLAMBDA),FLUX(NLAMBDA)
       DOUBLE PRECISION LINE
      
       COMMON/CROSS/NC,NL,WLL(400),SGL(400),WLC(400),SGC(400)

       LINE = 0.0

C Calculate by summing over all channels
       
       IF (NL.EQ.0) RETURN
      
       DO I=1,NL
          WVL=WLL(I)
          LINE=LINE+XJ(LAMBDA,NLAMBDA,FLUX,WVL)*SGL(I)
       END DO
      
       RETURN
      
       END

CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C Calculate photodissociation due to continuum
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      SUBROUTINE CALC_CONT(LAMBDA,NLAMBDA,FLUX,CONT)
      
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      
      DOUBLE PRECISION LAMBDA(NLAMBDA),FLUX(NLAMBDA)
      DOUBLE PRECISION LINE
      
      COMMON/CROSS/NC,NL,WLL(400),SGL(400),WLC(400),SGC(400)

      CONT = 0.0
      
C Calculate using numerical integration over wavelength

      IF (NC.EQ.0) RETURN
      
      XL=WLC(1)
      
      FL=SGC(1)*XJ(LAMBDA,NLAMBDA,FLUX,XL)
      
      DO I=2,NC
        
         XU=WLC(I)
        
         FU=SGC(I)*XJ(LAMBDA,NLAMBDA,FLUX,XU)
        
         CONT = CONT + 0.5*(XU-XL)*(FU+FL)
        
         XL=XU
        
         FL=FU
               
      END DO
      
      RETURN
      
      END
      
             
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C FUNCTION: XJ
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC

      FUNCTION XJ(LAMBDA,NLAMBDA,FLUX,WV)
      
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      
      DOUBLE PRECISION LAMBDA(NLAMBDA),FLUX(NLAMBDA)
      DOUBLE PRECISION LINE
      
      PARAMETER (PI=3.14159265)

      XJ = 0.0
       
      IF(WV.LE.912.) THEN
         
         RETURN
      
      ELSE IF (WV.LE.10000.0) THEN

C Interpolate flux 
         
         DO I=2,NLAMBDA
            IF ((WV.GE.LAMBDA(I-1)).AND.(WV.LE.LAMBDA(I))) THEN
               XJ = 4*PI*(FLUX(I-1)
     *         +(WV-LAMBDA(I-1))
     *         *(FLUX(I)-FLUX(I-1))
     *         /(LAMBDA(I)-LAMBDA(I-1)))
            END IF
         END DO
         
      ELSE
         
         XJ = 4*PI*FLUX(NLAMBDA)

      END IF
      
      RETURN
      
      END
