#!/bin/bash
gfortran -O2 -w -std=legacy -o disk_model disk_inputmodel.f disk_main.f ./Rate12_Chemistry/rate12_full_odes_v2.f dvode_drive.f dvode.f photo_rates.f shielding.f xray_rates.f zeta_x.f ismana.f
